#include <cstdio>
#include <cstdlib>
using namespace std;
int main()
{
	start:
	char ans;
	printf ("请输入要进行的计算：\n圆、圆柱、圆锥、球请输入1\n正方形、长方形、正方体、长方体请输入2\n三角形请输入3\n梯形请输入4\n平行四边形请输入5\n输入--->");
	scanf ("%s",&ans);
	if(ans=='1'){
		double pi,r,d,c,s,h,vzhu,szhu,vzhui,sqiu,vqiu;
		pi=3.14159265358979323846;
		printf("请输入半径与高......\n");
		printf ("半径=");
		scanf ("%lf",&r);
		printf ("高=");
		scanf ("%lf",&h);
		d=2*r;
		c=pi*d;
		s=pi*r*r;
		vzhu=s*h;
		szhu=2*pi*r*r+2*pi*r*h;
		vzhui=vzhu/3.0;
		vqiu=4/3*pi*r*r*r;
		sqiu=4*pi*r*r;
		printf (" \n");
		printf ("计算已经全部成功完成\n");
		printf ("圆周率=");
		printf ("%lf\n",pi);
		printf ("半径=");
		printf ("%lf\n",r);
		printf ("圆的直径=");
		printf ("%lf\n",d);
		printf ("圆的周长=");
		printf ("%lf\n",c);
		printf ("圆的面积=");
		printf ("%lf\n",s);
		printf ("圆柱的体积=");
		printf ("%lf\n",vzhu);
		printf ("圆柱的表面积=");
		printf ("%lf\n",szhu);
		printf ("圆锥的体积=");
		printf ("%lf\n",vzhui);
		printf ("球的体积=");
		printf ("%lf\n",vqiu);
		printf ("球的表面积=");
		printf ("%lf\n",sqiu);
		printf ("运行完毕，感谢使用\n");
		return 0;
	}else if(ans=='2'){
		double a,b,h,c,s,bmj,v;
		printf ("请输入长、宽、高......\n");
		printf ("长=");
		scanf ("%lf",&a);
		printf ("宽=");
		scanf ("%lf",&b);
		printf ("高=");
		scanf ("%lf",&h);
		c=(a+b)*2;
		s=a*b;
		bmj=(a*b+a*h+b*h)*2;
		v=a*b*h;
		printf (" \n");
		printf ("计算已经全部成功完成\n");
		printf ("长或边长=");
		printf ("%lf\n",a);
		printf ("宽或边长=");
		printf ("%lf\n",b);
		printf ("高=");
		printf ("%lf\n",h);
		printf ("长方形或正方形的周长=");
		printf ("%lf\n",c);
		printf ("长方形或正方形的面积=");
		printf ("%lf\n",s);
		printf ("长方体或正方体的表面积=");
		printf ("%lf\n",bmj);
		printf ("长方体或正方体的体积=");
		printf ("%lf\n",v);
		printf ("运行完毕，感谢使用\n");
		return 0;
	}else if(ans=='3'){
		double a,h,s;
		printf ("请输入底和高......\n");
		printf ("a=");
		scanf ("%lf",&a);
		printf ("h=");
		scanf ("%lf",&h);
		s=a*h/2.0;
		printf (" \n");
		printf ("计算已经全部成功完成\n");
		printf ("底=");
		printf ("%lf\n",a);
		printf ("高=");
		printf ("%lf\n",h);
		printf ("面积=");
		printf ("%lf\n",s);
		printf ("运行完毕，感谢使用\n");
		return 0;
	}else if(ans=='4'){
		double a,b,h,s;
		printf ("请输入上底、下底和高......\n");
		printf ("上底=");
		scanf ("%lf",&a);
		printf ("下底=");
		scanf ("%lf",&b);
		printf ("高=");
		scanf ("%lf",&h);
		s=(a+b)*h/2.0;
		printf (" \n");
		printf ("计算已经全部成功完成\n");
		printf ("上底=");
		printf ("%lf\n",a);
		printf ("下底=");
		printf ("%lf\n",b);
		printf ("高=");
		printf ("%lf\n",h);
		printf ("面积=");
		printf ("%lf\n",s);
		printf ("运行完毕，感谢使用\n");
		return 0;
	}else if(ans=='5'){
		double a,h,s;
		printf ("请输入底和高......\n");
		printf ("底=");
		scanf ("%lf",&a);
		printf ("高=");
		scanf ("%lf",&h);
		s=a*h;
		printf (" \n");
		printf ("计算已经全部成功完成\n");
		printf ("底=");
		printf ("%lf\n",a);
		printf ("高=");
		printf ("%lf\n",h);
		printf ("面积=");
		printf ("%lf\n",s);
		printf ("运行完毕，感谢使用\n");
		return 0;
	}else {
		printf ("乖，别闹，好好输入嘛~~~\n");
		system ("pause");
		system ("cls");
		goto start;
	}
}
